
git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : @project.name@
    description : @project.description@
    version : @project.version@
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : user-profile-service
  data :
    mongodb :
      uri : ${MONGODB_SERVER_URI:mongodb://sa_mongo:sa_mongo@localhost:27017/userprofiledb?authSource=admin}
  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false

  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

  zipkin :
    base-url : ${ZIPKIN_HOST:http://127.0.0.1:9411/}
    enabled : true

logging :
  level :
    ROOT : INFO
  pattern :
    console : "${spring.application.name} %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%X{transactionId},%X{traceId:-},%X{spanId:-}]){blue}[%thread] %clr(%-5level) %clr(%logger{36}){magenta} - %msg%n"

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

eureka :
  client :
    serviceUrl :
      defaultZone : ${EUREKA_SERVER_URL:http://service-registry:8080/eureka/}
    register-with-eureka : true
    fetch-registry : true

logbook :
  exclude :
    - /actuator/**
    - /v3/**
    - /swagger-ui/**
    - /swagger-resources/**
    - /metrics
  filter :
    enabled : true
  format :
    style : json
  obfuscate :
    headers :
      - Authorization
      - X-Secret
    parameters :
      - access_token
      - password
  minimum-status : ${MINIMUM_STATUS_LOG_BODY:400}

management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
        info : info
      base-path : /
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
    prometheus :
      enabled : true
    info :
      enabled : true

embedded :
  mongodb :
    enabled : false

ujar :
  restful-client :
    connect-timeout : ${RESTFUL_CLIENT_CONNECT_TIMEOUT:1s}
    read-timeout : ${RESTFUL_CLIENT_READ_TIMEOUT:10s}
    max-conn-per-route : ${RESTFUL_CLIENT_MAX_CONN_PER_ROUTE:20}
    max-conn-total : ${RESTFUL_CLIENT_MAX_CONN_TOTAL:2}
    retry :
      max-attempts : ${RESTFUL_CLIENT_RETRY_MAX_ATTEMPTS:3}
      delay : ${RESTFUL_CLIENT_RETRY_DELAY:1000}
      multiplier : ${RESTFUL_CLIENT_RETRY_MULTIPLIER:1.5}
      max-delay : ${RESTFUL_CLIENT_RETRY_MAX_DELAY:3000}

  restful-api-resources :
    department-service-base-url : ${DEPARTMENT_SERVICE_BASE_URL:http://department-service}
    department-service-uri : /api/v1/departments/{id}
