build :
  description : '@project.description@'
  relative-path : ${SWAGGER_RELATIVE_PATH:}
  version : '@project.version@'

git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : service-registry

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

eureka :
  client :
    register-with-eureka : false
    fetch-registry : false

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    prometheus :
      enabled : true
    info :
      enabled : true
