# This configuration is intended for development purpose
version : '3.8'
services :
  mongodb :
    image : mongo:5.0-focal
    container_name : acmedepartments-mongodb
    restart : unless-stopped
    ports :
      - 27017:27017
    environment :
      - MONGO_INITDB_ROOT_USERNAME=sa_mongo
      - MONGO_INITDB_ROOT_PASSWORD=sa_mongo
      - MONGO_INITDB_DATABASE=userprofiledb

  mysql :
    image : mysql:5.7.34
    container_name : acmedepartments-mysql
    restart : unless-stopped
    ports :
      - 3306:3306
    environment :
      - MYSQL_DATABASE=sa_test_db
      - MYSQL_USER=sa_test
      - MYSQL_PASSWORD=sa_test
      - MYSQL_ROOT_PASSWORD=sa_root
      - TZ=UTC

  zipkin:
    image: openzipkin/zipkin-slim:2.23
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dorg.slf4j.simpleLogger.log.zipkin2=debug
    ports:
      - 9411:9411
    depends_on:
      - storage

  storage:
    image: busybox:1.31.0
    container_name: fake_storage

  dependencies:
    image: busybox:1.31.0
    container_name: fake_dependencies

  prometheus :
    container_name : acmedepartments-prometheus
    image : prom/prometheus:v2.32.1
    volumes :
      - ./docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports :
      - 127.0.0.1:9090:9090
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : acmedepartments-grafana
    image : grafana/grafana:8.3.3
    volumes :
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports :
      - 127.0.0.1:3000:3000
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
