spring :
  config :
    import: configserver:${CONFIGSERVER_IMPORT:http://localhost:3002}

server :
  port : 3001
  shutdown : graceful

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
