build:
  description: '@project.description@'
  relative-path: ${SWAGGER_RELATIVE_PATH:}
  version: '@project.version@'

git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : api-gateway

  config :
    import : configserver:${CONFIGSERVER_IMPORT:http://localhost:3002}

  cloud :
    gateway :
      routes :
        - id : department-service
          uri : lb://department-service
          predicates :
            - Path=/api/v1/departments/**
          filters :
            - name : CircuitBreaker
              args :
                name : department-service
                fallbackuri : forward:/departmentServiceFallback

        - id : user-profile-service
          uri : lb://user-profile-service
          predicates :
            - Path=/api/v1/user-profiles/**
          filters :
            - name : CircuitBreaker
              args :
                name : user-profile-service
                fallbackuri : forward:/userProfileServiceFallback

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

eureka :
  client :
    serviceUrl :
      defaultZone : ${EUREKA_SERVER_URL:http://service-registry:8080/eureka/}
    register-with-eureka : true
    fetch-registry : true

hystrix :
  command :
    fallbackcmd :
      execution :
        isolation :
          thread :
            timeoutInMilliseconds : 4000


management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      exposure :
        include : health, prometheus, info, hystrix.stream
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    prometheus :
      enabled : true
    info :
      enabled : true
    hystrix :
      stream :
        enabled : true
  info :
    env :
      enabled : true
