build :
  version : @project.version@
  description : @project.description@
  relative-path : ${SWAGGER_RELATIVE_PATH:}

git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : @project.name@
    description : @project.description@
    version : @project.version@
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : config-server
  cloud :
    config :
      server :
        git :
          uri : https://github.com/dimdnk/ujar-config-server-example
          clone-on-start : true
server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

eureka :
  client :
    serviceUrl :
      defaultZone : ${EUREKA_SERVER_URL:http://service-registry:8080/eureka/}
    register-with-eureka : true
    fetch-registry : true

management :
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
        info : info
      base-path : /
      exposure :
        include : health, prometheus, info
  endpoint :
    health :
      enabled : true
      show-details : always
    prometheus :
      enabled : true
    info :
      enabled : true
